=== bananas-repos/bibliotheca-tools/data-crow/import/game/games-export.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="data-crow-objects">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" ref="software-item"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>

    <xsd:element name="category" type="type-category"/>
    <xsd:complexType name="type-category">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="container" type="type-container"/>
    <xsd:complexType name="type-container">
        <xsd:sequence>
            <xsd:element name="item" type="xsd:string"/>
            <xsd:element name="available" type="xsd:boolean"/>
            <xsd:element name="parent" type="xsd:string"/>
            <xsd:element name="created" type="xsd:date"/>
            <xsd:element name="days" type="xsd:integer"/>
            <xsd:element name="days-loaned" type="xsd:integer"/>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="due-date" type="xsd:date"/>
            <xsd:element name="filehash" type="xsd:string"/>
            <xsd:element name="filehash-type" type="xsd:string"/>
            <xsd:element name="filename" type="xsd:string"/>
            <xsd:element name="filesize" type="xsd:integer"/>
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="item" type="xsd:string"/>
            <xsd:element name="label" type="xsd:string"/>
            <xsd:element name="lend-by" type="xsd:string"/>
            <xsd:element name="loan-end-date" type="xsd:date"/>
            <xsd:element name="loan-start-date" type="xsd:date"/>
            <xsd:element name="loan-status" type="xsd:string"/>
            <xsd:element name="modified" type="xsd:date"/>
            <xsd:element name="picture-front" type="xsd:string"/>
            <xsd:element name="container-type" type="xsd:string"/>
            <xsd:element name="tags"/>
            <xsd:element name="tags-list" type="xsd:string"/>
            <xsd:element name="user-long-text-field" type="xsd:string"/>
            <xsd:element name="user-numeric-field-1" type="xsd:integer"/>
            <xsd:element name="user-numeric-field-2" type="xsd:integer"/>
            <xsd:element name="user-short-text-field-1" type="xsd:string"/>
            <xsd:element name="user-short-text-field-2" type="xsd:string"/>
            <xsd:element name="description" type="xsd:string"/>
            <xsd:element name="items"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="country" type="type-country"/>
    <xsd:complexType name="type-country">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="developer" type="type-developer"/>
    <xsd:complexType name="type-developer">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="language" type="type-language"/>
    <xsd:complexType name="type-language">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="publisher" type="type-publisher"/>
    <xsd:complexType name="type-publisher">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="state" type="type-state"/>
    <xsd:complexType name="type-state">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="tag" type="type-tag"/>
    <xsd:complexType name="type-tag">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="software-item" type="type-software-item"/>
    <xsd:complexType name="type-software-item">
        <xsd:sequence>
            <xsd:element name="item" type="xsd:string"/>
            <xsd:element name="available" type="xsd:boolean"/>
            <xsd:element name="categories"/>
            <xsd:element name="categories-list" type="xsd:string"/>
            <xsd:element name="container"/>
            <xsd:element name="container-list" type="xsd:string"/>
            <xsd:element name="cooperative-multiplayer" type="xsd:boolean"/>
            <xsd:element name="countries"/>
            <xsd:element name="countries-list" type="xsd:string"/>
            <xsd:element name="created" type="xsd:date"/>
            <xsd:element name="days" type="xsd:integer"/>
            <xsd:element name="days-loaned" type="xsd:integer"/>
            <xsd:element name="description" type="xsd:string"/>
            <xsd:element name="developers"/>
            <xsd:element name="developers-list" type="xsd:string"/>
            <xsd:element name="due-date" type="xsd:date"/>
            <xsd:element name="ean" type="xsd:string"/>
            <xsd:element name="filehash" type="xsd:string"/>
            <xsd:element name="filehash-type" type="xsd:string"/>
            <xsd:element name="filename" type="xsd:string"/>
            <xsd:element name="filesize" type="xsd:integer"/>
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="item" type="xsd:string"/>
            <xsd:element name="item-value" type="xsd:string"/>
            <xsd:element name="label" type="xsd:string"/>
            <xsd:element name="languages"/>
            <xsd:element name="languages-list" type="xsd:string"/>
            <xsd:element name="lend-by" type="xsd:string"/>
            <xsd:element name="license" type="xsd:string"/>
            <xsd:element name="loan-end-date" type="xsd:date"/>
            <xsd:element name="loan-start-date" type="xsd:date"/>
            <xsd:element name="loan-status" type="xsd:string"/>
            <xsd:element name="modified" type="xsd:date"/>
            <xsd:element name="multiplayer-game" type="xsd:boolean"/>
            <xsd:element name="picture-back" type="xsd:string"/>
            <xsd:element name="picture-cd" type="xsd:string"/>
            <xsd:element name="picture-front" type="xsd:string"/>
            <xsd:element name="platform" type="xsd:string"/>
            <xsd:element name="publishers"/>
            <xsd:element name="publishers-list" type="xsd:string"/>
            <xsd:element name="rating" type="xsd:integer"/>
            <xsd:element name="screenshot-one" type="xsd:string"/>
            <xsd:element name="screenshot-three" type="xsd:string"/>
            <xsd:element name="screenshot-two" type="xsd:string"/>
            <xsd:element name="serial-key" type="xsd:string"/>
            <xsd:element name="service" type="xsd:string"/>
            <xsd:element name="service-url" type="xsd:string"/>
            <xsd:element name="state"/>
            <xsd:element name="state-list" type="xsd:string"/>
            <xsd:element name="storage-medium" type="xsd:string"/>
            <xsd:element name="tags"/>
            <xsd:element name="tags-list" type="xsd:string"/>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="user-long-text-field" type="xsd:string"/>
            <xsd:element name="user-numeric-field-1" type="xsd:integer"/>
            <xsd:element name="user-numeric-field-2" type="xsd:integer"/>
            <xsd:element name="user-short-text-field-1" type="xsd:string"/>
            <xsd:element name="user-short-text-field-2" type="xsd:string"/>
            <xsd:element name="version" type="xsd:string"/>
            <xsd:element name="webpage" type="xsd:string"/>
            <xsd:element name="year" type="xsd:integer"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="tags">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="tag"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="items">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="item"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="categories">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="category"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="container">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="container"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="countries">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="country"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="developers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="developer"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="languages">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="language"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="publishers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="publisher"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="state">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="state"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== bananas-repos/bibliotheca-tools/data-crow/import/game/games-export.xml
<?xml version="1.0" encoding="UTF-8" ?>
<data-crow-objects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="games-export.xsd">
    <software-item>
        <item>Software</item>
        <available>true</available>
        <categories>
        </categories>
<categories-list></categories-list>
        <container>
        </container>
<container-list></container-list>
        <cooperative-multiplayer></cooperative-multiplayer>
        <countries>
        </countries>
<countries-list></countries-list>
        <created>2015-09-23</created>
        <days></days>
        <days-loaned></days-loaned>
        <description></description>
        <developers>
        </developers>
<developers-list></developers-list>
        <due-date></due-date>
        <ean></ean>
        <filehash></filehash>
        <filehash-type></filehash-type>
        <filename></filename>
        <filesize></filesize>
        <id>00a34000-fded-443f-a5bf-05df96a48f6c</id>
        <item>Software</item>
        <item-value></item-value>
        <label>Red Ocean</label>
        <languages>
        </languages>
<languages-list></languages-list>
        <lend-by></lend-by>
        <license></license>
        <loan-end-date></loan-end-date>
        <loan-start-date></loan-start-date>
        <loan-status>Available</loan-status>
        <modified>2015-09-23</modified>
        <multiplayer-game></multiplayer-game>
        <picture-back></picture-back>
        <picture-cd></picture-cd>
        <picture-front></picture-front>
        <platform></platform>
        <publishers>
        </publishers>
<publishers-list></publishers-list>
        <rating></rating>
        <screenshot-one></screenshot-one>
        <screenshot-three></screenshot-three>
        <screenshot-two></screenshot-two>
        <serial-key></serial-key>
        <service></service>
        <service-url></service-url>
        <state>
        </state>
<state-list></state-list>
        <storage-medium></storage-medium>
        <tags>
            <tag>
                <name>trekstor/games_1</name>
            </tag>
        </tags>
<tags-list>trekstor/games_1</tags-list>
        <title>Red Ocean</title>
        <user-long-text-field></user-long-text-field>
        <user-numeric-field-1></user-numeric-field-1>
        <user-numeric-field-2></user-numeric-field-2>
        <user-short-text-field-1></user-short-text-field-1>
        <user-short-text-field-2></user-short-text-field-2>
        <version></version>
        <webpage></webpage>
        <year></year>
    </software-item>
    <software-item>
        <item>Software</item>
        <available>true</available>
        <categories>
        </categories>
<categories-list></categories-list>
        <container>
        </container>
<container-list></container-list>
        <cooperative-multiplayer></cooperative-multiplayer>
        <countries>
        </countries>
<countries-list></countries-list>
        <created>2015-09-23</created>
        <days></days>
        <days-loaned></days-loaned>
        <description></description>
        <developers>
        </developers>
<developers-list></developers-list>
        <due-date></due-date>
        <ean></ean>
        <filehash></filehash>
        <filehash-type></filehash-type>
        <filename></filename>
        <filesize></filesize>
        <id>040ddce9-77c4-404a-b9f8-275aa46146f1</id>
        <item>Software</item>
        <item-value></item-value>
        <label>Sins of a Solar Empire</label>
        <languages>
        </languages>
<languages-list></languages-list>
        <lend-by></lend-by>
        <license></license>
        <loan-end-date></loan-end-date>
        <loan-start-date></loan-start-date>
        <loan-status>Available</loan-status>
        <modified>2015-09-23</modified>
        <multiplayer-game></multiplayer-game>
        <picture-back></picture-back>
        <picture-cd></picture-cd>
        <picture-front></picture-front>
        <platform></platform>
        <publishers>
        </publishers>
<publishers-list></publishers-list>
        <rating></rating>
        <screenshot-one></screenshot-one>
        <screenshot-three></screenshot-three>
        <screenshot-two></screenshot-two>
        <serial-key></serial-key>
        <service></service>
        <service-url></service-url>
        <state>
        </state>
<state-list></state-list>
        <storage-medium></storage-medium>
        <tags>
            <tag>
                <name>trekstor/games_3</name>
            </tag>
        </tags>
<tags-list>trekstor/games_3</tags-list>
        <title>Sins of a Solar Empire</title>
        <user-long-text-field></user-long-text-field>
        <user-numeric-field-1></user-numeric-field-1>
        <user-numeric-field-2></user-numeric-field-2>
        <user-short-text-field-1></user-short-text-field-1>
        <user-short-text-field-2></user-short-text-field-2>
        <version></version>
        <webpage></webpage>
        <year></year>
    </software-item>
    <software-item>
        <item>Software</item>
        <available>true</available>
        <categories>
        </categories>
<categories-list></categories-list>
        <container>
        </container>
<container-list></container-list>
        <cooperative-multiplayer></cooperative-multiplayer>
        <countries>
        </countries>
<countries-list></countries-list>
        <created>2015-09-23</created>
        <days></days>
        <days-loaned></days-loaned>
        <description></description>
        <developers>
        </developers>
<developers-list></developers-list>
        <due-date></due-date>
        <ean></ean>
        <filehash></filehash>
        <filehash-type></filehash-type>
        <filename></filename>
        <filesize></filesize>
        <id>04128f95-301c-4786-87d6-679ba7c6b9d3</id>
        <item>Software</item>
        <item-value></item-value>
        <label>Need for Speed: Porsche Unleashed</label>
        <languages>
        </languages>
<languages-list></languages-list>
        <lend-by></lend-by>
        <license></license>
        <loan-end-date></loan-end-date>
        <loan-start-date></loan-start-date>
        <loan-status>Available</loan-status>
        <modified>2015-09-23</modified>
        <multiplayer-game></multiplayer-game>
        <picture-back></picture-back>
        <picture-cd></picture-cd>
        <picture-front></picture-front>
        <platform></platform>
        <publishers>
        </publishers>
<publishers-list></publishers-list>
        <rating></rating>
        <screenshot-one></screenshot-one>
        <screenshot-three></screenshot-three>
        <screenshot-two></screenshot-two>
        <serial-key></serial-key>
        <service></service>
        <service-url></service-url>
        <state>
        </state>
<state-list></state-list>
        <storage-medium></storage-medium>
        <tags>
            <tag>
                <name>trekstor/games_3</name>
            </tag>
        </tags>
<tags-list>trekstor/games_3</tags-list>
        <title>Need for Speed: Porsche Unleashed</title>
        <user-long-text-field></user-long-text-field>
        <user-numeric-field-1></user-numeric-field-1>
        <user-numeric-field-2></user-numeric-field-2>
        <user-short-text-field-1></user-short-text-field-1>
        <user-short-text-field-2></user-short-text-field-2>
        <version></version>
        <webpage></webpage>
        <year></year>
    </software-item>
    <software-item>
        <item>Software</item>
        <available>true</available>
        <categories>
        </categories>
<categories-list></categories-list>
        <container>
        </container>
<container-list></container-list>
        <cooperative-multiplayer></cooperative-multiplayer>
        <countries>
        </countries>
<countries-list></countries-list>
        <created>2015-09-23</created>
        <days></days>
        <days-loaned></days-loaned>
        <description></description>
        <developers>
        </developers>
<developers-list></developers-list>
        <due-date></due-date>
        <ean></ean>
        <filehash></filehash>
        <filehash-type></filehash-type>
        <filename></filename>
        <filesize></filesize>
        <id>04136ffe-9237-4bdc-b958-90170db139db</id>
        <item>Software</item>
        <item-value></item-value>
        <label>Need for Speed: Carbon</label>
        <languages>
        </languages>
<languages-list></languages-list>
        <lend-by></lend-by>
        <license></license>
        <loan-end-date></loan-end-date>
        <loan-start-date></loan-start-date>
        <loan-status>Available</loan-status>
        <modified>2015-09-23</modified>
        <multiplayer-game></multiplayer-game>
        <picture-back></picture-back>
        <picture-cd></picture-cd>
        <picture-front></picture-front>
        <platform></platform>
        <publishers>
        </publishers>
<publishers-list></publishers-list>
        <rating></rating>
        <screenshot-one></screenshot-one>
        <screenshot-three></screenshot-three>
        <screenshot-two></screenshot-two>
        <serial-key></serial-key>
        <service></service>
        <service-url></service-url>
        <state>
        </state>
<state-list></state-list>
        <storage-medium></storage-medium>
        <tags>
            <tag>
                <name>trekstor/games_3</name>
            </tag>
        </tags>
<tags-list>trekstor/games_3</tags-list>
        <title>Need for Speed: Carbon</title>
        <user-long-text-field></user-long-text-field>
        <user-numeric-field-1></user-numeric-field-1>
        <user-numeric-field-2></user-numeric-field-2>
