=== bananas-repos/bibliotheca-tools/data-crow/import/movie/movies-export.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="data-crow-objects">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" ref="movie"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>

    <xsd:element name="actor" type="type-actor"/>
    <xsd:complexType name="type-actor">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="language" type="type-language"/>
    <xsd:complexType name="type-language">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="container" type="type-container"/>
    <xsd:complexType name="type-container">
        <xsd:sequence>
            <xsd:element name="item" type="xsd:string"/>
            <xsd:element name="description" type="xsd:string"/>
            <xsd:element name="available" type="xsd:boolean"/>
            <xsd:element name="created" type="xsd:date"/>
            <xsd:element name="days" type="xsd:integer"/>
            <xsd:element name="days-loaned" type="xsd:integer"/>
            <xsd:element name="icon" type="xsd:string"/>
            <xsd:element name="due-date" type="xsd:date"/>
            <xsd:element name="filehash" type="xsd:string"/>
            <xsd:element name="filehash-type" type="xsd:string"/>
            <xsd:element name="filename" type="xsd:string"/>
            <xsd:element name="filesize" type="xsd:integer"/>
            <xsd:element name="picture-front" type="xsd:string"/>
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="item" type="xsd:string"/>
            <xsd:element name="label" type="xsd:string"/>
            <xsd:element name="lend-by" type="xsd:string"/>
            <xsd:element name="loan-end-date" type="xsd:date"/>
            <xsd:element name="loan-start-date" type="xsd:date"/>
            <xsd:element name="loan-status" type="xsd:string"/>
            <xsd:element name="modified" type="xsd:date"/>
            <xsd:element name="tags"/>
            <xsd:element name="tags-list" type="xsd:string"/>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="user-long-text-field" type="xsd:string"/>
            <xsd:element name="user-numeric-field-1" type="xsd:integer"/>
            <xsd:element name="user-numeric-field-2" type="xsd:integer"/>
            <xsd:element name="user-short-text-field-1" type="xsd:string"/>
            <xsd:element name="user-short-text-field-2" type="xsd:string"/>
            <xsd:element name="container-type" type="xsd:string"/>
            <xsd:element name="items"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="country" type="type-country"/>
    <xsd:complexType name="type-country">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="director" type="type-director"/>
    <xsd:complexType name="type-director">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="genre" type="type-genre"/>
    <xsd:complexType name="type-genre">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="tag" type="type-tag"/>
    <xsd:complexType name="type-tag">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:element name="movie" type="type-movie"/>
    <xsd:complexType name="type-movie">
        <xsd:sequence>
            <xsd:element name="item" type="xsd:string"/>
            <xsd:element name="actors"/>
            <xsd:element name="actors-list" type="xsd:string"/>
            <xsd:element name="aspect-ratio" type="xsd:string"/>
            <xsd:element name="audio-bitrate" type="xsd:string"/>
            <xsd:element name="audio-channels" type="xsd:string"/>
            <xsd:element name="audio-codec" type="xsd:string"/>
            <xsd:element name="audio-languages"/>
            <xsd:element name="audio-languages-list" type="xsd:string"/>
            <xsd:element name="audio-sample-rate" type="xsd:string"/>
            <xsd:element name="available" type="xsd:boolean"/>
            <xsd:element name="certification" type="xsd:string"/>
            <xsd:element name="color" type="xsd:string"/>
            <xsd:element name="container"/>
            <xsd:element name="container-list" type="xsd:string"/>
            <xsd:element name="countries"/>
            <xsd:element name="countries-list" type="xsd:string"/>
            <xsd:element name="created" type="xsd:date"/>
            <xsd:element name="days" type="xsd:integer"/>
            <xsd:element name="days-loaned" type="xsd:integer"/>
            <xsd:element name="description" type="xsd:string"/>
            <xsd:element name="directors"/>
            <xsd:element name="directors-list" type="xsd:string"/>
            <xsd:element name="due-date" type="xsd:date"/>
            <xsd:element name="ean" type="xsd:string"/>
            <xsd:element name="episode-nr" type="xsd:integer"/>
            <xsd:element name="episode-name" type="xsd:string"/>
            <xsd:element name="filehash" type="xsd:string"/>
            <xsd:element name="filehash-type" type="xsd:string"/>
            <xsd:element name="filename" type="xsd:string"/>
            <xsd:element name="filesize" type="xsd:integer"/>
            <xsd:element name="fps" type="xsd:string"/>
            <xsd:element name="frames" type="xsd:string"/>
            <xsd:element name="genres"/>
            <xsd:element name="genres-list" type="xsd:string"/>
            <xsd:element name="height" type="xsd:string"/>
            <xsd:element name="id" type="xsd:string"/>
            <xsd:element name="item" type="xsd:string"/>
            <xsd:element name="item-value" type="xsd:string"/>
            <xsd:element name="label" type="xsd:string"/>
            <xsd:element name="languages"/>
            <xsd:element name="languages-list" type="xsd:string"/>
            <xsd:element name="lend-by" type="xsd:string"/>
            <xsd:element name="loan-end-date" type="xsd:date"/>
            <xsd:element name="loan-start-date" type="xsd:date"/>
            <xsd:element name="loan-status" type="xsd:string"/>
            <xsd:element name="modified" type="xsd:date"/>
            <xsd:element name="picture-back" type="xsd:string"/>
            <xsd:element name="picture-cd" type="xsd:string"/>
            <xsd:element name="picture-front" type="xsd:string"/>
            <xsd:element name="playlength" type="xsd:integer"/>
            <xsd:element name="rating" type="xsd:integer"/>
            <xsd:element name="season" type="xsd:string"/>
            <xsd:element name="series" type="xsd:string"/>
            <xsd:element name="service" type="xsd:string"/>
            <xsd:element name="service-url" type="xsd:string"/>
            <xsd:element name="state" type="xsd:string"/>
            <xsd:element name="storage-medium" type="xsd:string"/>
            <xsd:element name="subtitle-languages"/>
            <xsd:element name="subtitle-languages-list" type="xsd:string"/>
            <xsd:element name="tags"/>
            <xsd:element name="tags-list" type="xsd:string"/>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="title-local" type="xsd:string"/>
            <xsd:element name="user-long-text-field" type="xsd:string"/>
            <xsd:element name="user-numeric-field-1" type="xsd:integer"/>
            <xsd:element name="user-numeric-field-2" type="xsd:integer"/>
            <xsd:element name="user-short-text-field-1" type="xsd:string"/>
            <xsd:element name="user-short-text-field-2" type="xsd:string"/>
            <xsd:element name="video-bitrate" type="xsd:string"/>
            <xsd:element name="video-codec" type="xsd:string"/>
            <xsd:element name="webpage" type="xsd:string"/>
            <xsd:element name="width" type="xsd:string"/>
            <xsd:element name="year" type="xsd:integer"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="tags">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="tag"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="items">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="item"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="actors">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="actor"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="audio-languages">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="language"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="container">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="container"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="countries">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="country"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="directors">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="director"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="genres">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="genre"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="languages">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="language"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="subtitle-languages">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element maxOccurs="unbounded" ref="language"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== bananas-repos/bibliotheca-tools/data-crow/import/movie/movies-export.xml
<?xml version="1.0" encoding="UTF-8" ?>
<data-crow-objects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="movies-export.xsd">
    <movie>
        <item>Movies</item>
        <actors>
            <actor>
                <name>Amber Heard</name>
            </actor>
            <actor>
                <name>Gary Oldman</name>
            </actor>
            <actor>
                <name>Harrison Ford</name>
            </actor>
            <actor>
                <name>Liam Hemsworth</name>
            </actor>
        </actors>
<actors-list>Amber Heard, Gary Oldman, Harrison Ford, Liam Hemsworth</actors-list>
        <aspect-ratio></aspect-ratio>
        <audio-bitrate></audio-bitrate>
        <audio-channels></audio-channels>
        <audio-codec></audio-codec>
        <audio-languages>
        </audio-languages>
<audio-languages-list></audio-languages-list>
        <audio-sample-rate></audio-sample-rate>
        <available>true</available>
        <certification>PG-13</certification>
        <color></color>
        <container>
        </container>
<container-list></container-list>
        <countries>
            <country>
                <name>France</name>
            </country>
            <country>
                <name>United States</name>
            </country>
        </countries>
<countries-list>France, United States</countries-list>
        <created>2015-09-22</created>
        <days></days>
        <days-loaned></days-loaned>
        <description>The high stakes thriller Paranoia takes us deep behind the scenes of global success to a deadly world of greed and deception. The two most powerful tech billionaires in the world (Harrison Ford and Gary Oldman) are bitter rivals with a complicated past who will stop at nothing to destroy each other. A young superstar (Liam Hemsworth), seduced by unlimited wealth and power falls between them, and becomes trapped in the middle of the twists and turns of their life-and-death game of corporate espionage. By the time he realizes his life is in danger, he is in far too deep and knows far too much for them to let him walk away.</description>
        <directors>
            <director>
                <name>Robert Luketic</name>
            </director>
        </directors>
<directors-list>Robert Luketic</directors-list>
        <due-date></due-date>
        <ean></ean>
        <episode-nr></episode-nr>
        <episode-name></episode-name>
        <filehash></filehash>
        <filehash-type></filehash-type>
        <filename></filename>
        <filesize></filesize>
        <fps></fps>
        <frames></frames>
        <genres>
            <genre>
                <name>Drama</name>
            </genre>
            <genre>
                <name>Thriller</name>
            </genre>
        </genres>
<genres-list>Drama, Thriller</genres-list>
        <height></height>
        <id>00330b7f-5df8-49fa-ad79-2d1eb8ebb38c</id>
        <item>Movies</item>
        <item-value></item-value>
        <label>Paranoia</label>
        <languages>
            <language>
                <name>English</name>
            </language>
        </languages>
<languages-list>English</languages-list>
        <lend-by></lend-by>
        <loan-end-date></loan-end-date>
        <loan-start-date></loan-start-date>
        <loan-status>Available</loan-status>
        <modified>2015-09-23</modified>
        <picture-back>file:///F:\Documents\tmp\movies-export_images\0efb720d-d9e5-406b-aa42-e356f9c544e9_PictureFront.jpg</picture-back>
        <picture-cd>file:///F:\Documents\tmp\movies-export_images\3edf49eb-0270-456d-a15d-e5ddcba302ed_PictureFront.jpg</picture-cd>
        <picture-front>file:///F:\Documents\tmp\movies-export_images\00330b7f-5df8-49fa-ad79-2d1eb8ebb38c_PictureFront.jpg</picture-front>
        <playlength></playlength>
        <rating>6 / 10</rating>
        <season></season>
        <series></series>
        <service>Imdb / us / none / value=[Paranoia]</service>
        <service-url>http://us.imdb.com/title/tt1413495</service-url>
        <state></state>
        <storage-medium></storage-medium>
        <subtitle-languages>
        </subtitle-languages>
<subtitle-languages-list></subtitle-languages-list>
        <tags>
            <tag>
                <name>Storage B</name>
            </tag>
        </tags>
<tags-list>Storage B</tags-list>
        <title>Paranoia</title>
        <title-local></title-local>
        <user-long-text-field></user-long-text-field>
        <user-numeric-field-1></user-numeric-field-1>
        <user-numeric-field-2></user-numeric-field-2>
        <user-short-text-field-1></user-short-text-field-1>
        <user-short-text-field-2></user-short-text-field-2>
        <video-bitrate></video-bitrate>
        <video-codec></video-codec>
        <webpage>http://us.imdb.com/title/tt1413495</webpage>
        <width></width>
        <year>2013</year>
    </movie>
    <movie>
        <item>Movies</item>
        <actors>
            <actor>
                <name>Camryn Manheim</name>
            </actor>
            <actor>
                <name>Hays Wellford</name>
            </actor>
            <actor>
                <name>James Freedson-Jackson</name>
            </actor>
            <actor>
                <name>Kevin Bacon</name>
            </actor>
        </actors>
<actors-list>Camryn Manheim, Hays Wellford, James Freedson-Jackson, Kevin Bacon</actors-list>
        <aspect-ratio></aspect-ratio>
        <audio-bitrate></audio-bitrate>
        <audio-channels></audio-channels>
        <audio-codec></audio-codec>
        <audio-languages>
        </audio-languages>
<audio-languages-list></audio-languages-list>
        <audio-sample-rate></audio-sample-rate>
        <available>true</available>
        <certification>R</certification>
        <color></color>
        <container>
        </container>
<container-list></container-list>
        <countries>
        </countries>
<countries-list></countries-list>
        <created>2016-03-13</created>
        <days></days>
        <days-loaned></days-loaned>
        <description>A pair of ten-year-olds find an abandoned cop car in a field. When they take it for a joyride, it seems like they could kill themselves at any moment. But things only get worse when the small town sheriff goes looking for his missing car. The kids find themselves in the center of a deadly game of cat and mouse they don&apos;t understand and the only way out is to go as fast as their cop car can take them.</description>
        <directors>
            <director>
                <name>Jon Watts</name>
            </director>
        </directors>
<directors-list>Jon Watts</directors-list>
        <due-date></due-date>
        <ean></ean>
        <episode-nr></episode-nr>
        <episode-name></episode-name>
        <filehash></filehash>
        <filehash-type></filehash-type>
        <filename></filename>
        <filesize></filesize>
        <fps></fps>
        <frames></frames>
        <genres>
            <genre>
                <name>Thriller</name>
            </genre>
        </genres>
<genres-list>Thriller</genres-list>
        <height></height>
        <id>a5c41732-a600-405e-bab4-c3fa24745277</id>
        <item>Movies</item>
        <item-value></item-value>
        <label>Cop Car</label>
        <languages>
        </languages>
<languages-list></languages-list>
        <lend-by></lend-by>
        <loan-end-date></loan-end-date>
        <loan-start-date></loan-start-date>
        <loan-status>Available</loan-status>
        <modified>2016-03-13</modified>
        <picture-back></picture-back>
        <picture-cd></picture-cd>
        <picture-front>file:///F:\Documents\tmp\movies-export_images\a5c41732-a600-405e-bab4-c3fa24745277_PictureFront.jpg</picture-front>
        <playlength></playlength>
        <rating>6 / 10</rating>
        <season></season>
        <series></series>
        <service>Imdb / us / none / value=[cop car]</service>
        <service-url>http://us.imdb.com/title/tt3813310</service-url>
        <state></state>
        <storage-medium></storage-medium>
        <subtitle-languages>
        </subtitle-languages>
<subtitle-languages-list></subtitle-languages-list>
        <tags>
            <tag>
                <name>Storage C</name>
            </tag>
        </tags>
<tags-list>Storage C</tags-list>
        <title>Cop Car</title>
        <title-local></title-local>
        <user-long-text-field></user-long-text-field>
        <user-numeric-field-1></user-numeric-field-1>
        <user-numeric-field-2></user-numeric-field-2>
        <user-short-text-field-1></user-short-text-field-1>
        <user-short-text-field-2></user-short-text-field-2>
        <video-bitrate></video-bitrate>
        <video-codec></video-codec>
        <webpage>http://us.imdb.com/title/tt3813310</webpage>
        <width></width>
        <year>2015</year>
    </movie>
</data-crow-objects>
